# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: mdmudassir0143@gmail.com
author_name: Mohammad Mudassir
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: docver

